/// Structured non-destructive action request generated by Guardian for Phase 4.
class Phase4ActionRequest {
  final String requestId;
  final String decisionId;
  final String targetPackageName;
  final String actionType; // e.g. "PROMPT_USER_PERMISSION_REVIEW", "NOTIFICATION_ONLY", "FLAG_FOR_MONITORING"
  final String reasoningSummary;
  final bool requiresUserApproval; // ALWAYS true in Phase 3/4 design

  Phase4ActionRequest({
    required this.requestId,
    required this.decisionId,
    required this.targetPackageName,
    required this.actionType,
    required this.reasoningSummary,
    this.requiresUserApproval = true,
  });

  Map<String, dynamic> toJson() => {
        'requestId': requestId,
        'decisionId': decisionId,
        'targetPackageName': targetPackageName,
        'actionType': actionType,
        'reasoningSummary': reasoningSummary,
        'requiresUserApproval': requiresUserApproval,
      };

  factory Phase4ActionRequest.fromJson(Map<String, dynamic> json) =>
      Phase4ActionRequest(
        requestId: json['requestId']?.toString() ?? '',
        decisionId: json['decisionId']?.toString() ?? '',
        targetPackageName: json['targetPackageName']?.toString() ?? '',
        actionType: json['actionType']?.toString() ?? 'PROMPT_USER_PERMISSION_REVIEW',
        reasoningSummary: json['reasoningSummary']?.toString() ?? '',
        requiresUserApproval: json['requiresUserApproval'] ?? true,
      );
}

/// Result of a Phase 4 action request handling.
class Phase4ActionResult {
  final String requestId;
  final bool handled;
  final String statusMessage;
  final DateTime timestamp;

  Phase4ActionResult({
    required this.requestId,
    required this.handled,
    required this.statusMessage,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  Map<String, dynamic> toJson() => {
        'requestId': requestId,
        'handled': handled,
        'statusMessage': statusMessage,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Interface defining the contract between Guardian and Phase 4 response layer.
abstract class Phase4ActionHandler {
  Future<Phase4ActionResult> handleActionRequest(Phase4ActionRequest request);
}
