import 'evidence.dart';
import 'severity_confidence.dart';
import '../interfaces/phase4_action_handler.dart';

/// Comprehensive structured decision output generated by Guardian with complete provenance.
class GuardianDecision {
  final String decisionId;
  final DateTime timestamp;
  final GuardianSeverity severity;
  final GuardianConfidence confidence;
  final String summary;
  final List<ObservedFact> observedEvidence;
  final List<Inference> inferences;
  final List<Uncertainty> uncertainties;
  final String reasoning;
  final String userFacingExplanation;
  final List<GuardianRecommendation> recommendations;
  final bool requiresUserAttention;
  final Phase4ActionRequest? phase4ActionRequest;
  final String responseSource;
  final String? fallbackCause;
  final String? providerUsed;
  final String? modelUsed;
  final int fallbackDepth;
  final String? fallbackReason;
  final int? httpStatus;
  final int? latencyMs;

  GuardianDecision({
    required this.decisionId,
    DateTime? timestamp,
    required this.severity,
    required this.confidence,
    required this.summary,
    required this.observedEvidence,
    required this.inferences,
    required this.uncertainties,
    required this.reasoning,
    required this.userFacingExplanation,
    required this.recommendations,
    required this.requiresUserAttention,
    this.phase4ActionRequest,
    this.responseSource = 'RULE_BASED_FALLBACK',
    this.fallbackCause,
    this.providerUsed,
    this.modelUsed,
    this.fallbackDepth = 0,
    this.fallbackReason,
    this.httpStatus,
    this.latencyMs,
  }) : timestamp = timestamp ?? DateTime.now();

  Map<String, dynamic> toJson() => {
        'decisionId': decisionId,
        'timestamp': timestamp.toIso8601String(),
        'severity': severity.name,
        'confidence': confidence.toJson(),
        'summary': summary,
        'observedEvidence': observedEvidence.map((e) => e.toJson()).toList(),
        'inferences': inferences.map((e) => e.toJson()).toList(),
        'uncertainties': uncertainties.map((e) => e.toJson()).toList(),
        'reasoning': reasoning,
        'userFacingExplanation': userFacingExplanation,
        'recommendations': recommendations.map((e) => e.toJson()).toList(),
        'requiresUserAttention': requiresUserAttention,
        'phase4ActionRequest': phase4ActionRequest?.toJson(),
        'responseSource': responseSource,
        'fallbackCause': fallbackCause,
        'providerUsed': providerUsed,
        'modelUsed': modelUsed,
        'fallbackDepth': fallbackDepth,
        'fallbackReason': fallbackReason,
        'httpStatus': httpStatus,
        'latencyMs': latencyMs,
      };

  factory GuardianDecision.fromJson(Map<String, dynamic> json) =>
      GuardianDecision(
        decisionId: json['decisionId']?.toString() ?? '',
        timestamp: json['timestamp'] != null
            ? DateTime.parse(json['timestamp'].toString())
            : DateTime.now(),
        severity: GuardianSeverityExtension.fromString(
            json['severity']?.toString() ?? 'LOW'),
        confidence: json['confidence'] is Map<String, dynamic>
            ? GuardianConfidence.fromJson(
                json['confidence'] as Map<String, dynamic>)
            : GuardianConfidence(
                score: 0.5, justification: 'Default fallback'),
        summary: json['summary']?.toString() ?? '',
        observedEvidence: (json['observedEvidence'] as List<dynamic>?)
                ?.map((e) => ObservedFact.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        inferences: (json['inferences'] as List<dynamic>?)
                ?.map((e) => Inference.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        uncertainties: (json['uncertainties'] as List<dynamic>?)
                ?.map((e) => Uncertainty.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        reasoning: json['reasoning']?.toString() ?? '',
        userFacingExplanation: json['userFacingExplanation']?.toString() ?? '',
        recommendations: (json['recommendations'] as List<dynamic>?)
                ?.map((e) =>
                    GuardianRecommendation.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        requiresUserAttention: json['requiresUserAttention'] == true,
        phase4ActionRequest: json['phase4ActionRequest'] != null
            ? Phase4ActionRequest.fromJson(
                json['phase4ActionRequest'] as Map<String, dynamic>)
            : null,
        responseSource: json['responseSource']?.toString() ?? 'RULE_BASED_FALLBACK',
        fallbackCause: json['fallbackCause']?.toString(),
        providerUsed: json['providerUsed']?.toString(),
        modelUsed: json['modelUsed']?.toString(),
        fallbackDepth: json['fallbackDepth'] is int ? json['fallbackDepth'] as int : 0,
        fallbackReason: json['fallbackReason']?.toString(),
        httpStatus: json['httpStatus'] is int ? json['httpStatus'] as int : null,
        latencyMs: json['latencyMs'] is int ? json['latencyMs'] as int : null,
      );
}
